create table public.birthday_replies (
  id bigint generated by default as identity primary key,
  profile_key text not null,
  recipient text not null,
  name text not null,
  message text not null,
  rating integer not null check (rating between 1 and 10),
  sent_at timestamptz not null default now()
);

create index birthday_replies_profile_key_sent_at_idx
  on public.birthday_replies (profile_key, sent_at);

alter table public.birthday_replies enable row level security;

create policy "Anyone can read birthday replies"
  on public.birthday_replies for select
  to anon
  using (true);

create policy "Anyone can send birthday replies"
  on public.birthday_replies for insert
  to anon
  with check (
    length(name) between 1 and 120
    and length(message) between 1 and 2000
    and rating between 1 and 10
  );
